start_parking_session:
  name: Start parkeerssessie
  description: Start een parkeerssessie voor een bepaald kenteken tot een bepaalde tijd
  fields:
    license_plate:
      name: Kenteken
      description: Het kenteken van de auto (bijv. "AB123CD")
      required: true
      selector:
        text:
    end_time:
      name: Eindtijd
      description: Tot wanneer de auto geparkeerd moet blijven (UTC!)
      required: true
      selector:
        datetime: